#!/usr/bin/env python3
"""
Daily Digest Email
Sends a daily summary of X monitor findings and other updates.

Usage:
  python3 tools/daily_digest.py
  python3 tools/daily_digest.py --test  # Send test email
"""

import json
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gmail_client import GmailClient
from x_multi_monitor import MONITORED_USERS, get_user_id, get_recent_tweets, load_state, format_tweet


BASE_DIR = Path(__file__).resolve().parent.parent
LOGS_DIR = BASE_DIR / "logs"
STATE_PATH = LOGS_DIR / "daily_digest_state.json"


def get_yesterday_tweets():
    """
    Get tweets from all monitored users from roughly the last 24 hours.

    Important: this intentionally does **not** use the X monitor's state file.
    The live monitor (`x_multi_monitor.py`) already advances its own state when
    it sees new tweets. If we reused that state here, the daily digest would
    frequently think there are "no new tweets" even when there were tweets
    earlier in the day that the monitor already processed.

    Instead, we fetch each user's recent tweets (API-limited window) and then
    filter by timestamp to approximate "last 24 hours." This keeps the digest
    independent and makes its view consistent regardless of how often the
    monitor runs.
    """
    from datetime import timedelta

    cutoff = datetime.utcnow() - timedelta(days=1)
    all_tweets = []

    for username in MONITORED_USERS:
        user_id = get_user_id(username)
        if not user_id:
            continue

        # Get up to 10 recent tweets and filter by created_at time.
        tweets = get_recent_tweets(user_id, since_id=None) or []
        recent = []
        for tweet in tweets:
            created_at = tweet.get("created_at")
            if not created_at:
                continue
            try:
                # created_at example: "2026-03-13T13:05:12.000Z"
                dt = datetime.strptime(created_at, "%Y-%m-%dT%H:%M:%S.%fZ")
            except ValueError:
                # Fallback if microseconds are missing
                try:
                    dt = datetime.strptime(created_at, "%Y-%m-%dT%H:%M:%SZ")
                except ValueError:
                    continue

            if dt >= cutoff:
                recent.append(tweet)

        if recent:
            all_tweets.append(
                {
                    "username": username,
                    "tweets": recent,
                }
            )

    return all_tweets


def _today_str() -> str:
    return datetime.now().strftime("%Y-%m-%d")


def _load_state():
    if not STATE_PATH.exists():
        return {}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except Exception:
        # If state is corrupt, ignore and start fresh.
        return {}


def _save_state(state: dict) -> None:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")


def _already_sent_today() -> bool:
    state = _load_state()
    return state.get("last_sent_date") == _today_str()


def _mark_sent_today() -> None:
    state = _load_state()
    state["last_sent_date"] = _today_str()
    _save_state(state)


def build_digest(tweets_data):
    """Build email digest content."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    lines = [
        f"# Daily Digest - {now}",
        f"",
        f"## X/Twitter Updates",
        f"",
    ]
    
    total_tweets = sum(len(u['tweets']) for u in tweets_data)
    
    if total_tweets == 0:
        lines.append("No new tweets from monitored accounts today.")
    else:
        lines.append(f"Found {total_tweets} new tweet(s) from {len(tweets_data)} account(s):")
        lines.append(f"")
        
        for user_data in tweets_data:
            username = user_data['username']
            tweets = user_data['tweets']
            
            lines.append(f"### @{username}")
            lines.append(f"")
            
            for tweet in reversed(tweets):  # Oldest first
                text = tweet.get('text', '')
                created = tweet.get('created_at', '')[:10]
                metrics = tweet.get('public_metrics', {})
                tweet_id = tweet.get('id', '')
                
                lines.append(f"**{created}**")
                lines.append(f"> {text}")
                lines.append(f"❤️ {metrics.get('like_count', 0)}  🔁 {metrics.get('retweet_count', 0)}  💬 {metrics.get('reply_count', 0)}")
                lines.append(f"🔗 https://x.com/i/status/{tweet_id}")
                lines.append(f"")
    
    lines.extend([
        f"---",
        f"*Monitored accounts: {', '.join(MONITORED_USERS.keys())}*",
        f"*Generated by Gerald - OpenClaw Daily Digest*",
    ])
    
    return '\n'.join(lines)


def send_digest(test_mode=False):
    """Send daily digest email."""
    print("Building daily digest...")

    if not test_mode and _already_sent_today():
        print("Daily digest already sent today; skipping email send.")
        return True
    
    tweets_data = get_yesterday_tweets()
    content = build_digest(tweets_data)
    
    if test_mode:
        print("\n" + "="*60)
        print(content)
        print("="*60)
        return
    
    print(f"Found {sum(len(u['tweets']) for u in tweets_data)} new tweets")
    
    # Send email
    gmail = GmailClient()
    if not gmail.authenticate():
        print("✗ Gmail authentication failed")
        return False
    
    today = datetime.now().strftime('%Y-%m-%d')
    subject = f"Daily Digest - {today}"
    
    try:
        gmail.send_email(
            to="jason@allgreatthings.io",
            subject=subject,
            body=content
        )
        _mark_sent_today()
        print(f"✓ Daily digest sent to jason@allgreatthings.io")
        return True
    except Exception as e:
        print(f"✗ Failed to send email: {e}")
        return False


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--test', action='store_true', help='Print digest without sending')
    args = parser.parse_args()
    
    send_digest(test_mode=args.test)
