#!/usr/bin/env python3
"""
Daily Digest Email
Sends a daily summary of X monitor findings and other updates.

Usage:
  python3 tools/daily_digest.py
  python3 tools/daily_digest.py --test  # Send test email
"""

import json
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gmail_client import GmailClient
from x_multi_monitor import MONITORED_USERS, get_user_id, get_recent_tweets, load_state, format_tweet


def get_yesterday_tweets():
    """Get tweets from all monitored users from the last 24 hours."""
    all_tweets = []
    state = load_state()
    
    for username in MONITORED_USERS:
        user_id = get_user_id(username)
        if not user_id:
            continue
        
        # Get tweets since last check
        last_id = state.get(username)
        tweets = get_recent_tweets(user_id, last_id)
        
        if tweets:
            all_tweets.append({
                'username': username,
                'tweets': tweets
            })
    
    return all_tweets


def build_digest(tweets_data):
    """Build email digest content."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    lines = [
        f"# Daily Digest - {now}",
        f"",
        f"## X/Twitter Updates",
        f"",
    ]
    
    total_tweets = sum(len(u['tweets']) for u in tweets_data)
    
    if total_tweets == 0:
        lines.append("No new tweets from monitored accounts today.")
    else:
        lines.append(f"Found {total_tweets} new tweet(s) from {len(tweets_data)} account(s):")
        lines.append(f"")
        
        for user_data in tweets_data:
            username = user_data['username']
            tweets = user_data['tweets']
            
            lines.append(f"### @{username}")
            lines.append(f"")
            
            for tweet in reversed(tweets):  # Oldest first
                text = tweet.get('text', '')
                created = tweet.get('created_at', '')[:10]
                metrics = tweet.get('public_metrics', {})
                tweet_id = tweet.get('id', '')
                
                lines.append(f"**{created}**")
                lines.append(f"> {text}")
                lines.append(f"❤️ {metrics.get('like_count', 0)}  🔁 {metrics.get('retweet_count', 0)}  💬 {metrics.get('reply_count', 0)}")
                lines.append(f"🔗 https://x.com/i/status/{tweet_id}")
                lines.append(f"")
    
    lines.extend([
        f"---",
        f"*Monitored accounts: {', '.join(MONITORED_USERS.keys())}*",
        f"*Generated by Gerald - OpenClaw Daily Digest*",
    ])
    
    return '\n'.join(lines)


def send_digest(test_mode=False):
    """Send daily digest email."""
    print("Building daily digest...")
    
    tweets_data = get_yesterday_tweets()
    content = build_digest(tweets_data)
    
    if test_mode:
        print("\n" + "="*60)
        print(content)
        print("="*60)
        return
    
    print(f"Found {sum(len(u['tweets']) for u in tweets_data)} new tweets")
    
    # Send email
    gmail = GmailClient()
    if not gmail.authenticate():
        print("✗ Gmail authentication failed")
        return False
    
    today = datetime.now().strftime('%Y-%m-%d')
    subject = f"Daily Digest - {today}"
    
    try:
        gmail.send_email(
            to="jason@allgreatthings.io",
            subject=subject,
            body=content
        )
        print(f"✓ Daily digest sent to jason@allgreatthings.io")
        return True
    except Exception as e:
        print(f"✗ Failed to send email: {e}")
        return False


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--test', action='store_true', help='Print digest without sending')
    args = parser.parse_args()
    
    send_digest(test_mode=args.test)
