#!/usr/bin/env python3
"""
Weekly OpenClaw Security Review
Checks for updates, security advisories, and changelog.

Usage:
  python3 tools/security_review.py
  python3 tools/security_review.py --email  # Send email report
"""

import json
import sys
import subprocess
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gmail_client import GmailClient


def check_git_updates():
    """Check if OpenClaw repo has updates."""
    try:
        result = subprocess.run(
            ['git', 'fetch', '--dry-run'],
            capture_output=True,
            text=True,
            cwd=Path(__file__).resolve().parent.parent
        )
        return result.returncode == 0 and result.stderr
    except:
        return None


def get_latest_commits():
    """Get recent commits from OpenClaw repo."""
    try:
        result = subprocess.run(
            ['git', 'log', '--oneline', '-10'],
            capture_output=True,
            text=True,
            cwd=Path(__file__).resolve().parent.parent
        )
        return result.stdout.strip() if result.returncode == 0 else None
    except:
        return None


def check_changelog():
    """Check for changelog updates."""
    changelog_path = Path(__file__).resolve().parent.parent / "CHANGELOG.md"
    if not changelog_path.exists():
        return None
    
    content = changelog_path.read_text()
    # Get first section (latest changes)
    lines = content.split('\n')
    recent = []
    for line in lines[:50]:
        if line.strip():
            recent.append(line)
        if len(recent) > 20:
            break
    return '\n'.join(recent)


def build_report():
    """Build security review report."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    lines = [
        f"# Weekly OpenClaw Security Review",
        f"",
        f"**Date:** {now}",
        f"",
        f"## Repository Status",
        f"",
    ]
    
    # Check for updates
    updates = check_git_updates()
    if updates:
        lines.append("⚠️ **Updates available** — Run `git pull` to update")
        lines.append(f"")
    else:
        lines.append("✓ Repository is up to date")
        lines.append(f"")
    
    # Recent commits
    commits = get_latest_commits()
    if commits:
        lines.append(f"### Recent Commits")
        lines.append(f"```")
        lines.append(commits)
        lines.append(f"```")
        lines.append(f"")
    
    # Changelog
    changelog = check_changelog()
    if changelog:
        lines.append(f"### Recent Changelog")
        lines.append(f"```")
        lines.append(changelog[:1000])  # Limit length
        lines.append(f"```")
        lines.append(f"")
    
    # Security recommendations
    lines.extend([
        f"## Security Recommendations",
        f"",
        f"- [ ] Review latest commits for security-related changes",
        f"- [ ] Check for dependency updates (run `npm audit` if applicable)",
        f"- [ ] Review OpenClaw GitHub releases for security advisories",
        f"- [ ] Ensure all API keys are rotated regularly",
        f"",
        f"---",
        f"*Generated by Gerald - OpenClaw Security Review*",
    ])
    
    return '\n'.join(lines)


def send_report():
    """Generate and send security review report."""
    print("Generating security review...")
    
    content = build_report()
    
    # Send email
    gmail = GmailClient()
    if not gmail.authenticate():
        print("✗ Gmail authentication failed")
        return False
    
    today = datetime.now().strftime('%Y-%m-%d')
    subject = f"Weekly Security Review - {today}"
    
    try:
        gmail.send_email(
            to="jason@allgreatthings.io",
            subject=subject,
            body=content
        )
        print(f"✓ Security review sent to jason@allgreatthings.io")
        return True
    except Exception as e:
        print(f"✗ Failed to send email: {e}")
        return False


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--email', action='store_true', help='Send email report')
    args = parser.parse_args()
    
    if args.email:
        send_report()
    else:
        print(build_report())
